Traceback (most recent call last):
  File "solution.py", line 10, in <module>
    p = gdb.debug(elf.path, aslr=False, gdbscript='\n'.join([
  File "/home/sam/.local/lib/python3.8/site-packages/pwnlib/context/__init__.py", line 1578, in setter
    return function(*a, **kw)
  File "/home/sam/.local/lib/python3.8/site-packages/pwnlib/gdb.py", line 589, in debug
    garbage2 = gdbserver.recvline_startswith(b"Remote debugging from host ", timeout=2)
  File "/home/sam/.local/lib/python3.8/site-packages/pwnlib/tubes/tube.py", line 614, in recvline_startswith
    return self.recvline_pred(lambda line: any(map(line.startswith, delims)),
  File "/home/sam/.local/lib/python3.8/site-packages/pwnlib/tubes/tube.py", line 528, in recvline_pred
    line = self.recvline(keepends=True)
  File "/home/sam/.local/lib/python3.8/site-packages/pwnlib/tubes/tube.py", line 496, in recvline
    return self.recvuntil(self.newline, drop = not keepends, timeout = timeout)
  File "/home/sam/.local/lib/python3.8/site-packages/pwnlib/tubes/tube.py", line 339, in recvuntil
    res = self.recv(timeout=self.timeout)
  File "/home/sam/.local/lib/python3.8/site-packages/pwnlib/tubes/tube.py", line 104, in recv
    return self._recv(numb, timeout) or b''
  File "/home/sam/.local/lib/python3.8/site-packages/pwnlib/tubes/tube.py", line 174, in _recv
    if not self.buffer and not self._fillbuffer(timeout):
  File "/home/sam/.local/lib/python3.8/site-packages/pwnlib/tubes/tube.py", line 153, in _fillbuffer
    data = self.recv_raw(self.buffer.get_fill_size())
  File "/home/sam/.local/lib/python3.8/site-packages/pwnlib/tubes/process.py", line 671, in recv_raw
    if not self.can_recv_raw(self.timeout):
  File "/home/sam/.local/lib/python3.8/site-packages/pwnlib/tubes/process.py", line 715, in can_recv_raw
    return select.select([self.proc.stdout], [], [], timeout) == ([self.proc.stdout], [], [])
KeyboardInterrupt
